[project]
name = "llm-integration"
version = "0.1.0"
description = "Practice for integrating an llm into a backend"
readme = "README.md"
authors = [
    { name = "segfaultering", email = "261435586+segfaultering@users.noreply.github.com" }
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "google-genai>=2.19.0",
    "pydantic-settings>=2.15.0",
]

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyrefly>=1.2.0",
    "ruff>=0.16.4",
]
